language: go
env:
  global:
    secure: "NsbPsieJoBXvzLwx6XYffg4/80nRqhV5dHZUP8mRTMkmndfuR+r5iY4Os7QYxzYC88i4bx8rh0yOIOtfzGuLnvnuQRMAGXBLekpw/r2kYX9Tgn879DGxu9IG1b0Z1wJmUu4tflNLNSfjn0pxYsI+jWpmHuRTpNeyCit92iSvvMDOKvJsvMncMFEy/sLDVZ1ij7w48RhSLO9IvA4SVUYt9D42VaHcJ05IGdGlFvuoJQWJvckAqVqTMNnLil6QVBZ5AgrcC8BCaafGFkFK/uqgZPRNIbFFcFXFtOBYGLV6H31HJGo9eD17E2QtUtQvBHBi8MmI8cvV9QdpL2WzviZuxBrJEH6Dob4xZNEH44rFP1wfGT97kaBAOLhPoO9TU5AfzTaVg5vvhcTSw9cbcb9jqli7j8sfUPVW8c6yk5loYa4YbKGVKmlwLPCgeT+3pqTo78Uaz1mqg83gg3UZkzou0UMHfN8K87AWrcqB8jeLp2gSk3NwGLVPmLaklQPlY746XKvz4zH0exuCpyUGG3Bq6Fo2Cb9Wg0WZwoNDP6Hw8epvsIcItN8kIFTgiHbq2RBzCWNBS2ZgsAYX+oFAwiAwBzN5nTqmaVv/M6lAfQpMkJtQLZ2G+D1vENiPOxI/U8s8lmQj/6zoQoB6mZbLTN92tJv5wi0PS25mHKW8JCvrY8Q="
install:
  - GOOS=darwin GOARCH=amd64 go get -x -t -v ./...
  - GOOS=linux GOARCH=amd64 go get -x -t -v ./...
before_deploy:
  - for i in $GOPATH/bin/rdl-gen-parsec* ;do cp $i $i-linux;done
  - for i in $GOPATH/bin/darwin_amd64/rdl-gen-parsec*;do cp $i $GOPATH/bin/`basename $i`-darwin;done
  - zip -j rdl_gen.zip $GOPATH/bin/rdl-gen-parsec*-{darwin,linux}
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - git tag 0.1.$TRAVIS_BUILD_NUMBER -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
  - git push -q https://$GITHUBKEY@github.com/yahoo/parsec-rdl-gen --tags
deploy:
  provider: releases
  api_key:
    secure: YFi1ksNh45UXVW/MU6Y6qpOHQU2GHl9gHGJMKzHS/zFHNFCrvG4YUAE6gbwacDAfrCDSUVN+lKy3jHyI/WTiklAr//nalPXH78kytbvxeTBFkNvyjCGu9oUJuWciLKe1H/JSSVGBuU5aL2yo0jJikRJLqVf5aeoJay/dmzUYqt8ByUlkKH7pK4c5yrZqLSeog0iN85AZYyIF4wS/EaPRXwupuuSCbIMkxYmpVKJUu/HtQ9x2S8sAbGZH+VVXp+q3IfaFiRzPx9dVIfuqT9C+mgU10FMdMWgR9HdHpCTxlsSCXO+PneA6yl0veRSB84e7Xf27g+ebDfgfovZqrDRisHfgYtUHg/rp98EwEveN5yU58O5mN4FmZl3joZG14Toq1To8CRRdAPfy9e6uAdjk8u6B8z5HJ95O8B0gzkexzBe+edd+pQ9i643/8T4dCnEaJ+IUsku9G2Q64K0dYaHRCf6U/7NF53gleuceDukdR9arOEQYXAdlZwdcv5QlJDjXKCtNRa+6a+DMbG8sz9xJv6d8h2WyZ58g+YhNNNl5z0Dggw5tBZOubCWmIHlQogKR8ZFTxG+LPu6XqMXSjaojuYTFWjFBI6su8SR3ESBwgfEwRSiRUd1VFoLzpKpgGZnUb4RQ0PJoBpAhGElflgY3B8VZ2wSjxYNV6B4dbrUCkEw=
  skip_cleanup: true
  file: rdl_gen.zip
  on:
    repo: yahoo/parsec-rdl-gen
    tags: false
